-- =====================================================================
-- Hydrogen Lab Safety — Supabase setup script
-- Run this in the Supabase SQL Editor, top to bottom, in a single pass.
-- See README.md "Set up Supabase" for context and env-var/credential steps.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. TABLES
-- ---------------------------------------------------------------------

-- hazards: hotspot positions/text for the interactive lab.
-- "left" must be quoted as it is a reserved word in SQL.
-- module_section/module_id link a hotspot to a module; left nullable here
-- because the modules table (referenced by the FK below) doesn't exist yet.
create table public.hazards (
	type            text primary key,
	title           text not null,
	text            text not null,
	top             text not null,
	"left"          text not null,
	module_section  text null,
	module_id       text null,
	sort_order      int  not null default 0
);

-- modules / module_sections: content shared by every section under
-- app/modules/ (distinguished by the `section` column, e.g. 'hazard-modules').
create table public.modules (
  section       text not null,
  id            text not null,
  slug          text null,
  badge_num     integer null,
  icon          text not null,
  icon_bg       text not null,
  title         text not null,
  description   text not null,
  key_takeaway  text not null,
  prev_id       text null,
  next_id       text null,
  sort_order    integer not null default 0,
  constraint modules_pkey primary key (section, id)
);

create table public.module_sections (
  section     text not null,
  module_id   text not null,
  num         text not null,
  heading     text not null,
  body        text not null,
  list_type   text null,
  items       jsonb null,
  callout     text null,
  sort_order  integer not null default 0,
  constraint module_sections_pkey primary key (section, module_id, num),
  constraint module_sections_section_module_id_fkey foreign key (section, module_id) references modules (section, id) on delete cascade,
  constraint module_sections_list_type_check check ((list_type = any (array['ul'::text, 'ol'::text])))
);

-- Now that modules exists, add the FK deferred from hazards above.
alter table public.hazards
  add constraint hazards_module_fk
  foreign key (module_section, module_id)
  references public.modules (section, id)
  match full
  on delete set null;

-- profiles / user_module_progress / user_quiz_progress: accounts and
-- per-user training progress.
create table public.profiles (
  uid           text not null,
  email         text not null,
  role          text not null default 'user',
  user_type     text not null default 'public',
  organisation  text null,
  display_name  text null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint profiles_pkey primary key (uid),
  constraint profiles_email_key unique (email),
  constraint profiles_role_check check (role in ('user', 'staff', 'admin')),
  constraint profiles_user_type_check check (
    user_type in ('engineering_student', 'science_student', 'researcher', 'public', 'lecturer', 'teaching_staff')
  )
);

create table public.user_module_progress (
  id              uuid not null default gen_random_uuid(),
  uid             text not null,
  section         text not null,
  module_id       text not null,
  status          text not null default 'todo',
  progress        integer not null default 0,
  attempts        integer not null default 0,
  time_spent      integer not null default 0,
  started_at      timestamptz null,
  completed_at    timestamptz null,
  last_accessed   timestamptz null,
  created_at      timestamptz null default now(),
  updated_at      timestamptz null default now(),
  constraint user_module_progress_pkey primary key (id),
  constraint user_module_progress_uid_section_module_id_key unique (uid, section, module_id),
  constraint fk_user_progress foreign key (uid) references public.profiles (uid) on delete cascade,
  constraint fk_user_progress_module foreign key (section, module_id) references public.modules (section, id) on delete restrict,
  constraint user_module_progress_status_check check (status in ('todo', 'progress', 'done')),
  constraint user_module_progress_progress_check check (progress >= 0 and progress <= 100)
);

create table public.user_quiz_progress (
  id                  bigint generated by default as identity,
  uid                 text not null,
  quiz_id             text not null,
  score               integer not null default 0,
  attempts            integer not null default 0,
  passed              boolean not null default false,
  leaderboard_visible boolean not null default false,
  last_attempted_at   timestamptz null,
  created_at          timestamptz not null default now(),
  constraint user_quiz_progress_pkey primary key (id),
  constraint user_quiz_progress_uid_quiz_unique unique (uid, quiz_id)
);

-- ---------------------------------------------------------------------
-- 2. STORAGE BUCKET (for the lab image)
-- ---------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('lab-images', 'lab-images', true);

-- ---------------------------------------------------------------------
-- 3. PERMISSIONS (RLS + grants)
--
-- Note: `enable row level security` + a policy only controls which *rows*
-- a role can see/touch once it already has the base table-level privilege
-- for that operation — it does not grant that privilege itself. Tables
-- created via the SQL Editor (rather than the dashboard's table UI) don't
-- get this automatically, so without the explicit `grant`, every matching
-- query fails with `permission denied for table ...` (Postgres 42501)
-- even though the policy looks correct. Hence the grant lines below,
-- per table and per role.
-- ---------------------------------------------------------------------

-- hazards: public read, service-role write.
alter table public.hazards enable row level security;

create policy "Allow public read"
on public.hazards
for select
to anon
using (true);

create policy "Allow service role write"
on public.hazards
for all
to service_role
using (true)
with check (true);

grant select on public.hazards to anon;
grant insert, update, delete on public.hazards to service_role;

-- modules / module_sections: public read, service-role write.
alter table public.modules enable row level security;
alter table public.module_sections enable row level security;

create policy "Allow public read"
on public.modules
for select
to anon
using (true);

create policy "Allow service role write"
on public.modules
for all
to service_role
using (true)
with check (true);

create policy "Allow public read"
on public.module_sections
for select
to anon
using (true);

create policy "Allow service role write"
on public.module_sections
for all
to service_role
using (true)
with check (true);

grant select on public.modules to anon;
grant select on public.module_sections to anon;
grant insert, update, delete on public.modules to service_role;
grant insert, update, delete on public.module_sections to service_role;

-- Storage bucket access rules live on storage.objects rather than needing
-- RLS enabled or a grant select of their own.
create policy "Allow public read"
on storage.objects
for select
to anon
using (bucket_id = 'lab-images');

create policy "Allow service role upload"
on storage.objects
for insert
to service_role
with check (bucket_id = 'lab-images');

create policy "Allow service role update"
on storage.objects
for update
to service_role
using (bucket_id = 'lab-images');

-- profiles / user_module_progress / user_quiz_progress: every route
-- touching these three tables uses the service-role client (which
-- bypasses RLS) behind requireUser/requireAdmin, rather than the
-- browser-side anon client used for hazards/modules/module_sections.
-- So there's no anon select policy or grant here — enabling RLS with
-- no anon policies at all keeps them inaccessible to anything but the
-- service role.
alter table public.profiles enable row level security;
alter table public.user_module_progress enable row level security;
alter table public.user_quiz_progress enable row level security;
